// Skriv den rette datatype og et passende variabelnavn foran denne værdi: String teacherName= "Tess Løvgreen"
String teacherName  = "Tess Løvgreen";
int number = 365;
String bestCity = "København";
Boolean theTeacherIsGood =true;
int x = 60*24;
float percent = 22.12;
String hello  ="Hej, jeg heddder "+teacherName;
Boolean peterIsNotNice =false;
float kr = 2.2 + 33;
char skey ='S';
